version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    #volumes:
      #- ~/DockerVolumes/Mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - iot-network

  mysql:
    image: mysql:latest
    volumes:
      #- ~/DockerVolumes/MySQL/config/my.cnf:/etc/mysql/my.cnf
      - ~/DockerVolumes/MySQL/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    networks:
      - iot-network

  nodered:
    image: nodered/node-red:latest
    #volumes:
      #- ~/DockerVolumes/NodeRED/config/settings.js:/data/settings.js
      #- ~/DockerVolumes/NodeRED/data:/data
    ports:
      - "1880:1880"
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge